/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Controller.ClienteController;

/**
 *
 * @author flavi
 */
public class Cliente extends javax.swing.JFrame {
    private final ClienteController controller;
    /**
     * Creates new form Cliente
     */
    public Cliente() {
        initComponents();
        controller = new ClienteController(this);
        //iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLblCliente = new javax.swing.JLabel();
        jLblId = new javax.swing.JLabel();
        jLblNome = new javax.swing.JLabel();
        jLblSexo = new javax.swing.JLabel();
        jLblDtNascimento = new javax.swing.JLabel();
        jLblTelefone = new javax.swing.JLabel();
        jLblEmail = new javax.swing.JLabel();
        jLblRg = new javax.swing.JLabel();
        jLblEndereco = new javax.swing.JLabel();
        jLblCep = new javax.swing.JLabel();
        jTxtId = new javax.swing.JTextField();
        jTxtNome = new javax.swing.JTextField();
        jTxtDtNascimento = new javax.swing.JTextField();
        jTxtTelefone = new javax.swing.JTextField();
        jTxtRg = new javax.swing.JTextField();
        jTxtEmail = new javax.swing.JTextField();
        jTxtEndereco = new javax.swing.JTextField();
        jTxtCep = new javax.swing.JTextField();
        jRBMasculino = new javax.swing.JRadioButton();
        jRBFeminino = new javax.swing.JRadioButton();
        jBtnCadastrar = new javax.swing.JButton();
        jLblFundoEscuro = new javax.swing.JLabel();
        jLblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLblCliente.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLblCliente.setForeground(new java.awt.Color(255, 255, 255));
        jLblCliente.setText("Cliente");
        getContentPane().add(jLblCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, -1, -1));

        jLblId.setForeground(new java.awt.Color(255, 255, 255));
        jLblId.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLblId.setText("Id");
        getContentPane().add(jLblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, -1));

        jLblNome.setForeground(new java.awt.Color(255, 255, 255));
        jLblNome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLblNome.setText("Nome");
        getContentPane().add(jLblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, -1));

        jLblSexo.setForeground(new java.awt.Color(255, 255, 255));
        jLblSexo.setText("Sexo");
        getContentPane().add(jLblSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, -1, -1));

        jLblDtNascimento.setForeground(new java.awt.Color(255, 255, 255));
        jLblDtNascimento.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLblDtNascimento.setText("Data Nascimento");
        getContentPane().add(jLblDtNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, -1, -1));

        jLblTelefone.setForeground(new java.awt.Color(255, 255, 255));
        jLblTelefone.setText("Telefone");
        getContentPane().add(jLblTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, -1, -1));

        jLblEmail.setForeground(new java.awt.Color(255, 255, 255));
        jLblEmail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLblEmail.setText("E-mail");
        getContentPane().add(jLblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, -1, -1));

        jLblRg.setForeground(new java.awt.Color(255, 255, 255));
        jLblRg.setText("RG");
        getContentPane().add(jLblRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, -1, -1));

        jLblEndereco.setForeground(new java.awt.Color(255, 255, 255));
        jLblEndereco.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLblEndereco.setText("Endereço");
        getContentPane().add(jLblEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, -1, 20));

        jLblCep.setForeground(new java.awt.Color(255, 255, 255));
        jLblCep.setText("CEP");
        getContentPane().add(jLblCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 434, -1, 20));

        jTxtId.setEditable(false);
        jTxtId.setText("0");
        getContentPane().add(jTxtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 60, -1));
        getContentPane().add(jTxtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 330, -1));
        getContentPane().add(jTxtDtNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 90, -1));
        getContentPane().add(jTxtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 100, -1));
        getContentPane().add(jTxtRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 350, 120, -1));
        getContentPane().add(jTxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 330, -1));
        getContentPane().add(jTxtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 330, -1));
        getContentPane().add(jTxtCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 430, 120, -1));

        buttonGroup1.add(jRBMasculino);
        jRBMasculino.setForeground(new java.awt.Color(255, 255, 255));
        jRBMasculino.setText("Masculino");
        getContentPane().add(jRBMasculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, -1, -1));

        buttonGroup1.add(jRBFeminino);
        jRBFeminino.setForeground(new java.awt.Color(255, 255, 255));
        jRBFeminino.setText("Feminino");
        getContentPane().add(jRBFeminino, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 310, -1, -1));

        jBtnCadastrar.setText("Cadastrar");
        jBtnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 530, -1, -1));

        jLblFundoEscuro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLblFundoEscuro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Agenda-PainelFundo.png"))); // NOI18N
        getContentPane().add(jLblFundoEscuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 1270, 820));

        jLblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/AgendaFundo.png"))); // NOI18N
        getContentPane().add(jLblFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCadastrarActionPerformed
        controller.cadastrar();
    }//GEN-LAST:event_jBtnCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Cliente().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBtnCadastrar;
    private javax.swing.JLabel jLblCep;
    private javax.swing.JLabel jLblCliente;
    private javax.swing.JLabel jLblDtNascimento;
    private javax.swing.JLabel jLblEmail;
    private javax.swing.JLabel jLblEndereco;
    private javax.swing.JLabel jLblFundo;
    private javax.swing.JLabel jLblFundoEscuro;
    private javax.swing.JLabel jLblId;
    private javax.swing.JLabel jLblNome;
    private javax.swing.JLabel jLblRg;
    private javax.swing.JLabel jLblSexo;
    private javax.swing.JLabel jLblTelefone;
    private javax.swing.JRadioButton jRBFeminino;
    private javax.swing.JRadioButton jRBMasculino;
    private javax.swing.JTextField jTxtCep;
    private javax.swing.JTextField jTxtDtNascimento;
    private javax.swing.JTextField jTxtEmail;
    private javax.swing.JTextField jTxtEndereco;
    private javax.swing.JTextField jTxtId;
    private javax.swing.JTextField jTxtNome;
    private javax.swing.JTextField jTxtRg;
    private javax.swing.JTextField jTxtTelefone;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JRadioButton getjRBFeminino() {
        return jRBFeminino;
    }

    public void setjRBFeminino(javax.swing.JRadioButton jRBFeminino) {
        this.jRBFeminino = jRBFeminino;
    }

    public javax.swing.JRadioButton getjRBMasculino() {
        return jRBMasculino;
    }

    public void setjRBMasculino(javax.swing.JRadioButton jRBMasculino) {
        this.jRBMasculino = jRBMasculino;
    }

    public javax.swing.JTextField getjTxtCep() {
        return jTxtCep;
    }

    public void setjTxtCep(javax.swing.JTextField jTxtCep) {
        this.jTxtCep = jTxtCep;
    }

    public javax.swing.JTextField getjTxtDtNascimento() {
        return jTxtDtNascimento;
    }

    public void setjTxtDtNascimento(javax.swing.JTextField jTxtDtNascimento) {
        this.jTxtDtNascimento = jTxtDtNascimento;
    }

    public javax.swing.JTextField getjTxtEmail() {
        return jTxtEmail;
    }

    public void setjTxtEmail(javax.swing.JTextField jTxtEmail) {
        this.jTxtEmail = jTxtEmail;
    }

    public javax.swing.JTextField getjTxtEndereco() {
        return jTxtEndereco;
    }

    public void setjTxtEndereco(javax.swing.JTextField jTxtEndereco) {
        this.jTxtEndereco = jTxtEndereco;
    }

    public javax.swing.JTextField getjTxtId() {
        return jTxtId;
    }

    public void setjTxtId(javax.swing.JTextField jTxtId) {
        this.jTxtId = jTxtId;
    }

    public javax.swing.JTextField getjTxtNome() {
        return jTxtNome;
    }

    public void setjTxtNome(javax.swing.JTextField jTxtNome) {
        this.jTxtNome = jTxtNome;
    }

    public javax.swing.JTextField getjTxtRg() {
        return jTxtRg;
    }

    public void setjTxtRg(javax.swing.JTextField jTxtRg) {
        this.jTxtRg = jTxtRg;
    }

    public javax.swing.JTextField getjTxtTelefone() {
        return jTxtTelefone;
    }

    public void setjTxtTelefone(javax.swing.JTextField jTxtTelefone) {
        this.jTxtTelefone = jTxtTelefone;
    }

}
